spring:
  application:
    name: ONE
logging:
  config: classpath:logback-spring.xml

#server:
#  port: 8080
#  tomcat:
#    threads:
#      max: 200                # ??? ? ?? thread? ? ??
#      min-spare: 50           # ?? ??? ????(idle) thread? ??
#    accept-count: 100         # ?? ?? ???
#    max-connections: 8192
#    connection-timeout: 20000