spring:
  application:
    name: TWO

logging:
  config: classpath:logback-spring.xml

server:
  port: 8081
#  tomcat:
#    threads:
#      max: 200
#      min-spare: 10
#    max-connections: 8192
#    accept-count: 100 # Task queue size
#    connection-timeout: 20000