# Generated by Django 5.1 on 2024-08-13 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_no', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_no', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('tag_name', models.CharField(default=0, max_length=100, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_no', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('userId', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('blog_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pylog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('blog_tag_no', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('blog_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pylog.blog')),
                ('tag_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pylog.tags')),
            ],
        ),
    ]
