# Generated by Django 5.1 on 2024-08-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_no',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='blog_tag_no',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_no',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_no',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
