# Generated by Django 5.1 on 2024-08-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pylog", "0004_alter_blog_blog_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="updatedAt",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="comments",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="comments",
            old_name="updatedAt",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="tags",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="tags",
            old_name="updatedAt",
            new_name="updated_at",
        ),
    ]
