# Generated by Django 5.1 on 2024-08-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylog", "0005_rename_createdat_blog_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
