# Generated by Django 5.1 on 2024-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylog", "0006_alter_blog_created_at_alter_blog_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
