# Generated by Django 5.1 on 2024-08-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylog", "0007_alter_blog_created_at_alter_blog_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_no",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
