# Generated by Django 5.1 on 2024-08-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylog", "0008_alter_blog_blog_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogtag",
            name="blog_tag_no",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment_no",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tags",
            name="tag_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tags",
            name="tag_no",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
