CREATE DATABASE IF NOT EXISTS `friend`;
CREATE TABLE IF NOT EXISTS `friend` (
    id BIGINT PRIMARY KEY ,
    name VARCHAR(100)
);

CREATE USER user1@'%' IDENTIFIED BY 'user1';

GRANT ALL PRIVILEGES ON *.* TO 'user1'@'%';

FLUSH PRIVILEGES;
