spring:
  application:
    name: dev-test
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/h2/mybatis-test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  sql:
    init:
      mode: always